version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    labels:
      - dependencies
      - python
    commit-message:
      prefix: "build(deps)"
    groups:
      default:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - terraform
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "build(deps)"
