apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Aegis
  description: Vault-agnostic API broker with audit logging, built on FastAPI
  annotations:
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: yditj/projects/apps/Aegis
  links:
    - url: https://github.com/gustav0thethird/Aegis
      title: GitHub
      icon: github
  tags:
    - python
    - fastapi
    - secrets
    - devops
    - apps
spec:
  type: service
  lifecycle: production
  owner: gtully
  system: apps
