apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Aegis
  description: Aegis is a vendor-agnostic secrets broker and PAM gateway for managing
    API keys and secrets securely.
  annotations:
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: yditj/projects/apps/Aegis
    yditj.home/capabilities: Vendor-agnostic secrets management; Scoped API keys per
      team; Self-service webhook management; Key rotation management; Audit logging
      of all actions; Policy management for access control
  links:
  - url: https://github.com/gustav0thethird/Aegis
    title: GitHub
    icon: github
  tags:
  - secrets-management
  - api-gateway
  - team-self-service
  - logging
  - security
spec:
  type: service
  lifecycle: production
  owner: gtully
  system: apps
  providesApis:
  - Aegis-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Aegis-api
  description: HTTP API exposed by Aegis
spec:
  type: openapi
  lifecycle: production
  owner: gtully
  definition: "openapi: 3.0.0\ninfo:\n  title: Aegis API\n  version: 1.0.0\npaths:\n\
    \  /admin/api/settings:\n    get:\n      summary: Retrieve admin settings.\n \
    \     responses:\n        '200':\n          description: OK\n    put:\n      summary:\
    \ Update admin settings.\n      responses:\n        '200':\n          description:\
    \ OK\n  /admin/api/ping:\n    get:\n      summary: Ping the admin API to check\
    \ if it's alive.\n      responses:\n        '200':\n          description: OK\n\
    \  /admin/api/objects:\n    get:\n      summary: List all objects managed by the\
    \ admin.\n      responses:\n        '200':\n          description: OK\n    post:\n\
    \      summary: Create a new object.\n      responses:\n        '200':\n     \
    \     description: OK\n  /admin/api/changelog:\n    get:\n      summary: Retrieve\
    \ the change log.\n      responses:\n        '200':\n          description: OK\n"
